#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;



// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    int a;
    scanf("%d", &a);
    int count = 0;

    for (int i = 0; i < 3; i++)
    {
        if (a & (1 << i)) count++;
    }
    cout << count << endl;
    return 0;
}
