#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll A, ll B, ll C, ll X){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll A;
    scanf("%lld", &A);
    ll B;
    scanf("%lld", &B);
    ll C;
    scanf("%lld", &C);
    ll X;
    scanf("%lld", &X);
    solve(A, B, C, X);
    return 0;
}
