#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;

const ll MOD = 2;

void solve(ll N, vector<ll> A){
    int ans = 100;
    for (ll a : A) {
        int length = 0;
        while (a % 2 == 0) {
            a /= 2;
            length++;
        }
        ans = min(ans, length);
    }
    cout << ans << endl;
}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    vector<ll> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &A[i]);
    }
    solve(N, move(A));
    return 0;
}
