#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, ll Q, vector<ll> T){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    ll Q;
    scanf("%lld", &Q);
    vector<ll> T(Q);
    for(int i = 0 ; i < Q ; i++){
        scanf("%lld", &T[i]);
    }
    solve(N, Q, move(T));
    return 0;
}
