#include <bits/stdc++.h>
#include <atcoder/all>

using namespace std;
using namespace atcoder;

using ll = long long;


void solve(ll N, vector<ll> d){

}

// Generated by 2.16.0 https://github.com/kyuridenamida/atcoder-tools
int main(){
    ll N;
    scanf("%lld", &N);
    vector<ll> d(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld", &d[i]);
    }
    solve(N, move(d));
    return 0;
}
